services:
  - type: web
    name: mi-rincon-letras
    env: python
    region: oregon

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn letrasproject.wsgi:application"

    # HEALTH CHECK para que no revise "/"
    healthCheckPath: /healthz

    # Se ejecuta antes de desplegar
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py createsuperuser \
        --noinput \
        --username $DJANGO_SUPERUSER_USERNAME \
        --email $DJANGO_SUPERUSER_EMAIL || true

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      # Puedes dejar el resto de vars aquí o crearlas desde el panel de Render
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: dpwzm6e3w
      # - key: CLOUDINARY_API_KEY
      #   value: "736134723259348"
      # - key: CLOUDINARY_API_SECRET
      #   value: "xxxxx"
      # - key: DATABASE_URL
      #   value: "postgres://...."


