services:
  - type: web
    name: mi-rincon-letras
    env: python
    region: oregon

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn letrasproject.wsgi:application"

    healthCheckPath: /healthz

    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; import os; User = get_user_model(); username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin'); password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin123'); email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com'); user, created = User.objects.update_or_create(username=username, defaults={'email': email, 'is_staff': True, 'is_superuser': True}); user.set_password(password); user.save(); print('Superusuario listo:', username)"

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      # aquí puedes tener el resto de variables…


