services:
  - type: web
    name: mi-rincon-letras
    env: python
    region: oregon

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn letrasproject.wsgi:application"

    # HEALTH CHECK para que no revise "/"
    healthCheckPath: /healthz

    # Solo UNA vez
    preDeployCommand: "python manage.py migrate && python manage.py collectstatic --noinput"

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      # Aquí puedes agregar tus variables si quieres dejarlas fijas en YAML:
      # - key: CLOUDINARY_CLOUD_NAME
      #   value: dpwzm6e3w
      # - key: CLOUDINARY_API_KEY
      #   value: "736134723259348"
      # - key: CLOUDINARY_API_SECRET
      #   value: "xxxxx"
      # - key: DATABASE_URL
      #   value: "postgres://...."

