# Generated by Django 5.2.4 on 2025-07-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroleido',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libroleido',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('leyendo', 'Leyendo'), ('finalizado', 'Finalizado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20),
        ),
    ]
