# Generated by Django 5.2.4 on 2025-07-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libroleido_link_libroleido_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='link',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='libroleido',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='libroleido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='libroleido',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroleido',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroleido',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('abandonado', 'Abandonado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='resumen',
            field=models.TextField(),
        ),
    ]
