# Generated by Django 5.2.4 on 2025-07-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_remove_libro_link_remove_libro_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroleido',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=100),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
    ]
