# Generated by Django 5.2.4 on 2025-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_diariolector_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariolector',
            name='puntuacion',
            field=models.IntegerField(default=0),
        ),
    ]
