# Generated by Django 5.2.4 on 2025-09-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_diariolector_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='libroleido',
            name='categoria',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(to='biblioteca.categoria'),
        ),
        migrations.AddField(
            model_name='libroleido',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='biblioteca.categoria'),
        ),
    ]
