# Generated by Django 5.2.4 on 2025-10-14 00:09

import biblioteca.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_libro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='diariolector',
            name='frase_iconica',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='diariolector',
            name='nota_personal',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='diariolector',
            name='punto_clave',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='diariolector',
            name='puntuacion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ManyToManyField(blank=True, to='biblioteca.categoria'),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('iniciado', 'Iniciado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='libros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), biblioteca.models.validar_pdf]),
        ),
        migrations.AlterField(
            model_name='libroleido',
            name='resumen',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
