# Generated by Django 5.2.4 on 2025-11-08 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_categoria_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, help_text='Opcional. Úsalo si conoces el ISBN para mejores recomendaciones.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='libroleido',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, help_text='Opcional. Si existe, se usa para mejorar las recomendaciones.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Pendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'isbn', 'titulo')},
            },
        ),
    ]
