# Generated by Django 5.2.4 on 2025-11-16 19:57

from django.db import migrations


GENEROS = [
    "Acción", "Aventura", "Comedia", "Drama", "Romance", "Fantasía",
    "Ciencia Ficción", "Misterio", "Thriller", "Horror", "Histórico",
    "Bélico", "Psicológico", "Magia", "Sobrenatural", "Distopía",
    "Escolar", "Reencarnación", "Vida cotidiana", "Mitología", 
    "Viajes en el tiempo", "LGTB+", "Realismo mágico", "Juvenil",
    "Adulto", "Cuentos", "Manga/Manhwa", "Isekai", "Ensayo",
]

def crear_categorias(apps, schema_editor):
    Categoria = apps.get_model('biblioteca', 'Categoria')
    for nombre in GENEROS:
        Categoria.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '<<AQUÍ VA LA ÚLTIMA MIGRACIÓN ANTERIOR>>'),
    ]

    operations = [
        migrations.RunPython(crear_categorias),
    ]
