# Generated by Django 5.2.4 on 2025-11-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_libro_isbn_libroleido_isbn_pendiente'),
    ]

    operations = [
    ]
