# Generated by Django 5.2.4 on 2025-11-23 23:29

import biblioteca.models
import biblioteca.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_cargar_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroleido',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=biblioteca.storage.RawMediaCloudinaryStorage(), upload_to='libros/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), biblioteca.models.validar_pdf]),
        ),
    ]
